controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

kernel:
    resource: ../src/Kernel.php
    type: annotation


app_calendar_index:
    path: /calendar
    controller: App\Controller\CalendarController::index





