controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

kernel:
    resource: ../src/Kernel.php
    type: annotation


app_calendar_index:
    path: /calendar
    controller: App\Controller\CalendarController::index

footer_data:
  path: /footer-data
  controller: App\Controller\AdminController::footerData

app_calendar_available:
    path: /calendar/available
    controller: App\Controller\CalendarController::available



