controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

kernel:
    resource: ../src/Kernel.php
    type: annotation


app_calendar_index:
    path: /calendar
    controller: App\Controller\CalendarController::index

footer_data:
  path: /footer-data
  controller: App\Controller\AdminController::footerData

app_calendar_available_places:
    path: /calendar/available-places
    controller: App\Controller\CalendarController::availablePlaces

app_calendar_remaining_places:
    path: /calendar/remaining-places-api
    controller: App\Controller\CalendarController::remainingPlaces
    methods: GET


app_calendar_show:
    path: /calendar/show/{id}
    controller: App\Controller\CalendarController::show

app_calendar_edit:
    path: /calendar/{id}/edit
    controller: App\Controller\CalendarController::edit

app_calendar_delete:
    path: /calendar/delete/{id}
    controller: App\Controller\CalendarController::delete

admin_calendar_edit:
    path: /admin/calendarA/{id}/edit
    controller: App\Controller\Admin\AdminCalendarController::edit

admin_calendar_delete:
    path: /admin/calendarA/delete/{id}
    controller: App\Controller\Admin\AdminCalendarController::delete

admin_calendar_index:
    path: /admin/calendarA
    controller: App\Controller\Admin\AdminCalendarController::index





